### ISSUE TITLE
:cached_weighted_average is always 0.0

### ISSUE THREAD

**Issue by msbrigna** [ryanto/acts_as_votable#102]
When I vote with a weight for the resource, the value of :cached_weighted_average is not updating and remain 0.0.

service.vote_by :voter => current_user, :vote_weight => 4
service.cached_weighted_average.round(2) 
0.0

Is the value of :cached_weighted_average updated automatically?

**Comment by tb** [comment]
The rubygems version is 0.10.0 from June 8, 2014 (see http://rubygems.org/gems/acts_as_votable ) and does not include cached_weighted_average.

Change Gemfile to:

    gem 'acts_as_votable', github: 'ryanto/acts_as_votable'

and run

    bundle update acts_as_votable

**Comment by samcambridge** [comment]
I've done the above and still have the issue. Any suggestions?

**Comment by halilim** [comment]
@samcambridge Can you share some code and data? Is `cached_votes_total` and `cached_weighted_score` greater than zero? Do `cached_votes_total`, `cached_weighted_score`, `cached_weighted_average` etc exist in the table?
