### ISSUE TITLE
Changing it to a numerical rating system 

### ISSUE THREAD

**Issue by pwz2k** [ryanto/acts_as_votable#106]
Is it possible with this gem to configure it to do a voting scale of 1-10?

As I would like a 1-10 scale, show average rating for the photo, and only allow user to vote once on each photo.

I'm considering using the gem but didn't see any examples of how to do a 1-10 voting scale.

**Comment by epergo** [comment]
Answered by @halilim on 2014.

@pwz2k if you need information feel free to open a new issue, thanks!
