### ISSUE TITLE
WARNING: Can't mass-assign protected attributes for ActsAsVotable::Vote: votable, voter, vote_scope

### ISSUE THREAD

**Issue by Sri-K** [ryanto/acts_as_votable#107]
Hi,

I am a newbie and I got the following error.

WARNING: Can't mass-assign protected attributes for ActsAsVotable::Vote: votable, voter, vote_scope
    app/controllers/posts_controller.rb:44:in `upvote'

Please help me

Thanks

**Comment by virvit** [comment]
Hi. I don't understand :( 

I've the latest ActsAsVotable, so it should check rails version and strong params, but it still throws that error:

ActiveModel::MassAssignmentSecurity::Error:
       Can't mass-assign protected attributes for ActsAsVotable::Vote: votable, voter, vote_scope
     # /Users/virvit/.rvm/gems/ruby-2.1.2/gems/protected_attributes-1.0.8/lib/active_model/mass_assignment_security/sanitizer.rb:60:in `process_removed_attributes'
     # /Users/virvit/.rvm/gems/ruby-2.1.2/gems/protected_attributes-1.0.8/lib/active_model/mass_assignment_security/sanitizer.rb:10:in `sanitize'
     # /Users/virvit/.rvm/gems/ruby-2.1.2/gems/protected_attributes-1.0.8/lib/active_model/mass_assignment_security.rb:346:in `sanitize_for_mass_assignment'
     # /Users/virvit/.rvm/gems/ruby-2.1.2/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/attribute_assignment.rb:58:in `assign_attributes'
     # /Users/virvit/.rvm/gems/ruby-2.1.2/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/core.rb:8:in `init_attributes'
     # /Users/virvit/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.8/lib/active_record/core.rb:196:in `initialize'
     # /Users/virvit/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.8/lib/active_record/inheritance.rb:30:in `new'
     # /Users/virvit/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.8/lib/active_record/inheritance.rb:30:in `new'
     # /Users/virvit/.rvm/gems/ruby-2.1.2/gems/acts_as_votable-0.10.0/lib/acts_as_votable/votable.rb:87:in `vote_by'
     # /Users/virvit/.rvm/gems/ruby-2.1.2/gems/acts_as_votable-0.10.0/lib/acts_as_votable/voter.rb:39:in `vote'
     # /Users/virvit/.rvm/gems/ruby-2.1.2/gems/acts_as_votable-0.10.0/lib/acts_as_votable/voter.rb:43:in `vote_up_for'
