### ISSUE TITLE
Could not find generator acts_as_votable:migration

### ISSUE THREAD

**Issue by Komissarov** [ryanto/acts_as_votable#109]
Can't create migration.
ruby 1.9.3p551 
Rails 3.1.1

$ rails generate acts_as_votable:migration
Could not find generator acts_as_votable:migration.

**Comment by alexisllamas** [comment]
:( :ice_cream:

**Comment by epergo** [comment]
Closing because last comment was from December 2015.

Just remember, if you keep having this issue, don't hesitate to create another issue!
