### ISSUE TITLE
Migrations won't number properly if migrations aren't set to DateTime.

### ISSUE THREAD

**Issue by nkiermaier** [ryanto/acts_as_votable#118]
If I set the flag to go back to simple numbered migrations,  all of my other gems will create proper migrations, except for a_a_v.

config.active_record.timestamped_migrations = false 

Here's a s.o. about the issue:
http://stackoverflow.com/questions/3739893/how-to-use-simple-numbered-migrations-versions-in-rails

**Comment by epergo** [comment]
Hello @nkiermaier I'm sorry but we don't give support to old versioning of migrations. Anyway we only have 1 migration file so you can rename it by hand.
