### ISSUE TITLE
add active record association to vote.rb

### ISSUE THREAD

**Issue by pavankat** [ryanto/acts_as_votable#119]
I put this into my initializer file and it doesn't seem to add the association into it :(

config/initializers/votes.rb

```
module ActsAsVotable
    class Vote < ActiveRecord::Base
        has_many :discuss_reputation_changes, as: :reputable
    end
end
```

**Comment by pavankat** [comment]
basically when I have a DiscussReputationChange object, I want to be able to do this:

```
DiscussReputationChange.reputable 
```

and get the vote object.

I know to access it in the console, I need to do ActsAsVotable::Vote, so I think i'm missing something. Any chance someone can help me figure this out?

**Comment by epergo** [comment]
Hello @pavankat 

Please follow the guide in Readme, more specifically here https://github.com/ryanto/acts_as_votable#votable-models

You don't need an initializer with this gem, just add `acts_as_votable` to the model you want to be votable.

Hope it helps.
