### ISSUE TITLE
Why does `unvote_by` not work for scoped votes?

### ISSUE THREAD

**Issue by marcamillion** [ryanto/acts_as_votable#122]
I have a `Post` that has no votes:

```
[74] pry(main)> p.votes_for
=> []
```

Then I add a simple vote with a `vote_scope` like so:

```
[75] pry(main)> p.vote_by voter: a, vote_scope: :inspired
   (0.5ms)  SELECT COUNT(*) FROM "votes"  WHERE "votes"."votable_id" = $1 AND "votes"."votable_type" = $2 AND "votes"."voter_id" = 1 AND "votes"."vote_scope" = 'inspired' AND "votes"."voter_type" = 'User'  [["votable_id", 83], ["votable_type", "Post"]]
   (0.2ms)  BEGIN
  SQL (2.2ms)  INSERT INTO "votes" ("created_at", "updated_at", "votable_id", "votable_type", "vote_flag", "vote_scope", "vote_weight", "voter_id", "voter_type") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"  [["created_at", "2015-06-29 06:53:17.838517"], ["updated_at", "2015-06-29 06:53:17.838517"], ["votable_id", 83], ["votable_type", "Post"], ["vote_flag", "t"], ["vote_scope", "inspired"], ["vote_weight", 1], ["voter_id", 1], ["voter_type", "User"]]
   (0.5ms)  COMMIT
=> true
```

Which gives me this:

```
[76] pry(main)> p.votes_for.reload
  ActsAsVotable::Vote Load (0.4ms)  SELECT "votes".* FROM "votes"  WHERE "votes"."votable_id" = $1 AND "votes"."votable_type" = $2  [["votable_id", 83], ["votable_type", "Post"]]
=> [#<ActsAsVotable::Vote id: 6, votable_id: 83, votable_type: "Post", voter_id: 1, voter_type: "User", vote_flag: true, vote_scope: "inspired", vote_weight: 1, created_at: "2015-06-29 06:53:17", updated_at: "2015-06-29 06:53:17">]
```

All of that looks good.

However, when I try to `unvote` that record like so - it seems to go through:

```
[78] pry(main)> p.unvote_by a
   (0.5ms)  SELECT COUNT(*) FROM "votes"  WHERE "votes"."votable_id" = $1 AND "votes"."votable_type" = $2 AND "votes"."voter_id" = 1 AND "votes"."vote_scope" IS NULL AND "votes"."voter_type" = 'User'  [["votable_id", 83], ["votable_type", "Post"]]
=> true
```

Except when I check my original post, I still see the vote:

```
[79] pry(main)> p.votes_for.reload
  ActsAsVotable::Vote Load (0.3ms)  SELECT "votes".* FROM "votes"  WHERE "votes"."votable_id" = $1 AND "votes"."votable_type" = $2  [["votable_id", 83], ["votable_type", "Post"]]
=> [#<ActsAsVotable::Vote id: 6, votable_id: 83, votable_type: "Post", voter_id: 1, voter_type: "User", vote_flag: true, vote_scope: "inspired", vote_weight: 1, created_at: "2015-06-29 06:53:17", updated_at: "2015-06-29 06:53:17">]
[80] pry(main)> p.votes_for
=> [#<ActsAsVotable::Vote id: 6, votable_id: 83, votable_type: "Post", voter_id: 1, voter_type: "User", vote_flag: true, vote_scope: "inspired", vote_weight: 1, created_at: "2015-06-29 06:53:17", updated_at: "2015-06-29 06:53:17">]
[81] pry(main)> a.id
=> 1
```

Note that the [source code here](https://github.com/ryanto/acts_as_votable/blob/master/lib/acts_as_votable/votable.rb#L134-L136) and [the tests](https://github.com/ryanto/acts_as_votable/blob/master/spec/shared_example/votable_model_spec.rb#L107-L111) says this should work, so I am not sure what's happening.

What could be causing this?

**Edit 1**

Note that when I manually destroy the vote, it removes it properly as can be seen here:

```
[85] pry(main)> v = p.votes_for.last
=> #<ActsAsVotable::Vote id: 6, votable_id: 83, votable_type: "Post", voter_id: 1, voter_type: "User", vote_flag: true, vote_scope: "inspired", vote_weight: 1, created_at: "2015-06-29 06:53:17", updated_at: "2015-06-29 06:53:17">
[86] pry(main)> v.destroy
   (0.2ms)  BEGIN
  SQL (0.5ms)  DELETE FROM "votes" WHERE "votes"."id" = $1  [["id", 6]]
   (0.9ms)  COMMIT
=> #<ActsAsVotable::Vote id: 6, votable_id: 83, votable_type: "Post", voter_id: 1, voter_type: "User", vote_flag: true, vote_scope: "inspired", vote_weight: 1, created_at: "2015-06-29 06:53:17", updated_at: "2015-06-29 06:53:17">
[88] pry(main)> p.votes_for.reload
  ActsAsVotable::Vote Load (0.3ms)  SELECT "votes".* FROM "votes"  WHERE "votes"."votable_id" = $1 AND "votes"."votable_type" = $2  [["votable_id", 83], ["votable_type", "Post"]]
=> []
```

**Comment by marcamillion** [comment]
Ok I figured it out.

The way to do this is simply:

    p.unvote_by a, vote_scope: :inspired

This is how the entire successful unvoting log looks:

    [102] pry(main)> p.unvote_by a, vote_scope: :inspired
       (0.5ms)  SELECT COUNT(*) FROM "votes"  WHERE "votes"."votable_id" = $1 AND "votes"."votable_type" = $2 AND "votes"."voter_id" = 1 AND "votes"."vote_scope" = 'inspired' AND "votes"."voter_type" = 'User'  [["votable_id", 83], ["votable_type", "Post"]]
      ActsAsVotable::Vote Load (0.3ms)  SELECT "votes".* FROM "votes"  WHERE "votes"."votable_id" = $1 AND "votes"."votable_type" = $2 AND "votes"."voter_id" = 1 AND "votes"."vote_scope" = 'inspired' AND "votes"."voter_type" = 'User'  [["votable_id", 83], ["votable_type", "Post"]]
       (0.2ms)  BEGIN
      SQL (0.2ms)  DELETE FROM "votes" WHERE "votes"."id" = $1  [["id", 8]]
       (0.4ms)  COMMIT
       (1.9ms)  SELECT COUNT(*) FROM "votes"  WHERE "votes"."votable_id" = $1 AND "votes"."votable_type" = $2  [["votable_id", 83], ["votable_type", "Post"]]
    => true

**Comment by epergo** [comment]
Yep, you had to add the scope in order to unvote, I guess we could work a little bit more on docs.

So no issue here! Thanks to share.
