### ISSUE TITLE
Using different table name for 'votes'

### ISSUE THREAD

**Issue by rkgarg** [ryanto/acts_as_votable#13]
Is it possible to use a different table name for 'votes'.

Actually I am working on an engine and want to use acts_as_votable for models in my engine, so ideally I would like to have the table name like 'myengine_votes' .  I modified migration to use the different table name, but then the functions of this gem won't recognize the table...

**Comment by TheCrow1213** [comment]
Hey! I'm guessing this never got implemented / is not planned for implementation anymore? Just curious :]
