### ISSUE TITLE
undefined method `liked?'

### ISSUE THREAD

**Issue by Rubioli** [ryanto/acts_as_votable#134]
For some reason that I can't figure out, when I use `liked?`, `voted_on?` or  `voted_for?`, I get error `undefined method ...`

*My controller:*
```
def upvote
    @choice = Choice.friendly.find(params[:id])
    @choice.liked_by current_user
end
```

*My models*
```
class Choice < ActiveRecord::Base
  acts_as_votable
end

class User < ActiveRecord::Base
  acts_as_voter
end
````

*My route*
```
resources :choices do
    member do
      put "like", to: "choices#upvote"
    end
  end
```

And I have tried with this line of code to check if user has voted on a object/model:
```
- @user = current_user.id
- if @user.liked? @choice
    %h1 hallo
```

But I still get the error, but everything else works fine.

Hope someone can help me out.

Thanks in advanced!

**Comment by MyklClason** [comment]
This is a standards issue. This gem makes make use of the standard where a `?` is added to the end of methods that return a Boolean, so it should work if you remove the question marks.

**Comment by Rubioli** [comment]
Thanks for comment, no it didn't worked

**Comment by Rubioli** [comment]
I read the `gem`'s file and found out a better way and its `voted_on_by? ``
Ex: @object.voted_on_by? current_user
