### ISSUE TITLE
Adding additional voting options

### ISSUE THREAD

**Issue by Rubioli** [ryanto/acts_as_votable#136]
Right now the gem provides `likes` `dislikes` / `thumbs_up` `thumbs_down`. How can I/ Is it any method to add additional vote options to my gem?

What I am looking for is having **5 vote** options: `Like` `Hate` `Cool` `OMG` `Angry`, So users can choose between these and not only `thumbs_up`, `thumbs_down`.

Appreciate any help.
Thanks in advanced!

**Comment by lekkerduidelijk** [comment]
@Rubioli Did you find a solution for this? I'm looking for something alike.

**Comment by Rubioli** [comment]
Yeah, I made my own voting system. Then I could just add as many as I wanted. I wouldn't configure anything from the gem. 

Better to just build your own.

**Comment by lekkerduidelijk** [comment]
Thanks. Will do.

**Comment by Rubioli** [comment]
Good luck ;)
