### ISSUE TITLE
@post.votes.size not work

### ISSUE THREAD

**Issue by xupijack** [ryanto/acts_as_votable#137]
@post.votes_for.size # => 5
@post.get_likes.size # => 3
@post.get_upvotes.size # => 3
@post.get_dislikes.size # => 2
@post.get_downvotes.size # => 2

all this work, but in another part of tutorial
- Registered Votes

@user.likes @shoe
@user.likes @shoe

@shoe.votes # => 1
@shoe.likes # => 1
( In my testing, I use @post.votes )

it return NoMethodError: undefined method `votes'
I have acts_as_voter and acts_as_votable
Is this a mistaken in tutorial? or I do anything wrong?

**Comment by WilfredRuck** [comment]
The methods for Acts_As_Votable gem have been updated. Check out the Documentation here: https://github.com/ryanto/acts_as_votable#changes 
and scroll down to the bottom and check out CHANGES.

**Comment by epergo** [comment]
Closing because it is solved. Thx @WilfredRuck
