### ISSUE TITLE
Question: Seeing the voting history

### ISSUE THREAD

**Issue by alexmc6** [ryanto/acts_as_votable#138]
Am I right in thinking that acts_as_votable only stores the most recent vote - whether up, down, or unset?

What I would like is for each vote to be historized so we can see, for example, when a new vote is made we can see the old vote in the database but limited to the time until the new vote was made. 

I am thinking of something like one of the auditable ruby gems such as https://github.com/collectiveidea/audited or something else from https://www.ruby-toolbox.com/categories/Active_Record_Versioning

I assume I do something like this

```
class Vote < ActiveRecord::Base
  audited
end
```

However if I were to do this would I need to fork the acts_as_votable repo and create my own version of it?

Thanks

**Comment by joshuaplemon** [comment]
I am wondering about tracking changes/history/logs as well. It looks like gems such as audited, paper_trails, and public_activity will do the trick. Has anyone used a gem to track changes with acts_as_votable?

**Comment by ryanto** [comment]
I think for this one it's going to be best to use another gem that's made for tracking changes over time. In the past I've paper_trail for these sorts of thingns.
