### ISSUE TITLE
Any API endpoints suggestions?

### ISSUE THREAD

**Issue by benjaminb10** [ryanto/acts_as_votable#140]
Hi, I have a rails app API only.
An User can like or dislike a Message.

Which API endpoints do you suggest me using acts_as_votable?

For instance, those two endpoints will not be RESTful:
/message/like
/message/dislike

Should I create a resource like Vote with a user_id (the voter), message_id (the votable) and type (like, dislike, etc.).
So my endpoint will be:
/vote

Thanks for this gem.

**Comment by epergo** [comment]
Hello! What about this:

`/messages/message_id`           -> Show action of the message
`/messages/message_id/votes` -> Returns all votes of a message (maybe a summary, nº of likes, nº of dislikes)
`/messages/message_id/votes/user_id` -> Vote of the user for that message
`/messages/message_id/votes/user_id/like` -> Like the message
`/messages/message_id/votes/user_id/dislike` -> Dislike the message

So at the end, an url to dislike a message would be:

`/messages/42/votes/epergom/dislike`
