### ISSUE TITLE
issue : Votes only for one object

### ISSUE THREAD

**Issue by gichuru** [ryanto/acts_as_votable#141]
I seem to have an interesting issue, while all my comments are listed, it seems that only one comment is affected by the votes... i.e you have 5 comments, comment 1 to 5, if you vote on comment 5 the votes change on comment 1 instead of 5.. 

Any idea what I could be doing wrong??

**Comment by epergo** [comment]
Hi @gichuru ! Weird issue indeed. Maybe is because you are sending to the server the ID (or the field you use to identify a comment) of the comment 1 instead of 5.

Could you please provide an example app with the error?

**Comment by TopolinoHackerino** [comment]
Hello @epergo,

I am actually having the same issue of @gichuru.  

When I try to upvote an other object, from the same list, it upvote or downvote only the first record of the list. If i do it from console, with the same helper (upvote_by/ downvote_from) look like is working perfectly. 

In my controller : 
`
  def upvote
    @link = Link.find_by(params[:id])
    puts params[:id]
    @link.upvote_by current_user

    redirect_back(fallback_location: root_path)
  end
  def downvote
    @link = Link.find_by(params[:id])
    puts params[:id]
    @link.downvote_from current_user
    redirect_back(fallback_location: root_path)
  end`

In view :
`<% @links.each do |link| %>

  <div id="link-row" class="row clearfix">
   ...
   <%= link_to like_link_path(link), method: :put, class: "btn btn-light btn-sm" do %>
        <%= fa_icon "arrow-up" %> Upvote
        <%= link.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_link_path(link), method: :put, class: "btn btn-light btn-sm" do %>
        <%= fa_icon "arrow-down" %> Downvote
        <%= link.get_dislikes.size %>
      <% end %>
...
<% end %>`

it's something I miss?
This solution should work fine on Rails 4, but on Rails 5 it seems to be some bug? 

Thank you,
Topolino

**Comment by epergo** [comment]
Mmm your code seems right and is weird that, as you said, in console works using exactly the same helpers

Could you debug it using something like pry? Just to be sure that the controller is receiving what it should

**Comment by TopolinoHackerino** [comment]
@epergo ,

I have tried to debug with pry, it seems that is always receiving the :id param with number 2, even if you press for a button that should have an :id of 6 for exemple. The route goes, I can see from console to get the right data, but when it comes to get the id from the view, is always 2...

```

Started PUT "/links/3/like" for 127.0.0.1 at 2018-12-08 20:49:35 +0100
   (0.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
  ↳ /Users/andrei/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1.1/lib/active_record/log_subscriber.rb:98
Processing by LinksController#upvote as HTML
  Parameters: {"authenticity_token"=>"ki6kgyvGyyD9pSupWq8AH1OAo+OC9Lv2zQ3gbDvy2X4DNOMEIYA7WnXs6aOX9jPGNmo5M6kdHngydmiozvXelw==", "id"=>"3"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ /Users/andrei/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1.1/lib/active_record/log_subscriber.rb:98
  Link Load (0.2ms)  SELECT  "links".* FROM "links" WHERE (3) LIMIT ?  [["LIMIT", 1]]
  ↳ app/controllers/links_controller.rb:74

From: /Users/andrei/RubyProjects/Rails/12in12/Redit/app/controllers/links_controller.rb @ line 75 LinksController#upvote:

    73: def upvote
    74:   @link = Link.find_by(params[:id])
 => 75:   binding.pry
    76:   @link.upvote_by current_user
    77: 
    78:   redirect_back(fallback_location: root_path)
    79: end

[1] pry(#<LinksController>)> @link.id
[1] pry(#<LinksController>)> @link.id=> 2

```

**Comment by TopolinoHackerino** [comment]
Wow, I'm such a noob...
Yes, that seams to be my stupid fault. Shame on me(like for real).

I've started studying Rails like 3 months ago and I didn't realize that there was a 
`find_by` 
and 
`find`
method. 
So yeah, I will keep working on my skills.
So, yes, it seems it works great even on Rails 5.

Thank you @epergo.

**Comment by epergo** [comment]
No prob! I make those mistakes everyday :sweat_smile:
