### ISSUE TITLE
Add migration version for Rails5

### ISSUE THREAD

**Issue by Jake-Day-Williams** [ryanto/acts_as_votable#142]
Rails 5+ needs migrations to indicate the version. This is returned otherwise:
"Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:"

I've fixed this on my local version of acts_as_votable. I would like to create a pull request if possible. Thanks.

**Comment by dlehman** [comment]
@Jake-Day-Williams In the meantime, care to share so the rest of us can hack in Rails5 support?

**Comment by Jake-Day-Williams** [comment]
@dlehman Yep.
Go into your migration file that was generated and add '[5.1]' to the end of the first line.
class ActsAsVotableMigration < ActiveRecord::Migration
to
class ActsAsVotableMigration < ActiveRecord::Migration[5.1]

This assumes you're using Rails 5.1.

Assuming I can get this pulled I've created methods to do this automatically when the migration file is generated. We'll see. No response yet.

**Comment by dlehman** [comment]
@Jake-Day-Williams Thank-you, I appreciate the response.

**Comment by epergo** [comment]
Hello @Jake-Day-Williams !! We already have a pending pull request for this matter #146 , right now is pending revision.

Could you please share your opinion on that pull request? Thank you for your time!

**Comment by epergo** [comment]
Solved on #146
