### ISSUE TITLE
Can i have specific columns

### ISSUE THREAD

**Issue by ltenzil** [ryanto/acts_as_votable#144]
Hi Thanks for providing a awesome gem. 
Can i have only specific columns AddCachedVotesToPosts. Let say, i dont want to update weight cache and other weight related columns. Is all mandatory or columns are optional

Thanks for your time.

**Comment by epergo** [comment]
Hi @ltenzil , `AddCachedVotesToPosts` migration if fully customizable. For example if you only want to speed up total votes of your model, your migration will be:

``` ruby
class AddCachedVotesToPosts < ActiveRecord::Migration
  def self.up
    add_column :posts, :cached_votes_total, :integer, :default => 0
    add_index  :posts, :cached_votes_total
  end
end
```
You just have to create the migration and add the columns you want

**Comment by ltenzil** [comment]
Awesome, Thank @epergo , i thought there are some methods which use those columns.
