### ISSUE TITLE
rails db:migrate

### ISSUE THREAD

**Issue by Murali-Mohan-M** [ryanto/acts_as_votable#145]
= 20170613100500 AddDeviseToUsers: migrating =================================
-- change_table(:users)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: no such table: users: ALTER TABLE "users" ADD "email" varchar DEFAULT '' NOT NULL

**Comment by laertispappas** [comment]
@Murali-Mohan-M Exception is raise when you try to run 20170613100500 AddDeviseToUser. This has nothing to do with `acts_as_votable` gem
