### ISSUE TITLE
Could not find generator acts_as_votable:migration

### ISSUE THREAD

**Issue by trilukevo** [ryanto/acts_as_votable#152]
Rails  version 5.1

$ rails generate acts_as_votable:migration
Could not find generator acts_as_votable:migration.

**Comment by epergo** [comment]
Hi @trilukevo I have just tried it and it works. Did you run `bundle install` before trying to generate migrations?

What version of the gem are you using? The one in the master branch? The one in rubygems?

**Comment by trilukevo** [comment]
Hi @epergo ! Yeah I don't know what happened with `bundle install` so I use another command line `gem install` instead and it works so far.
My gem version is 2.6.12? is that right? I use `gem -v` to check.
Sorry I'm a very new person to coding.

**Comment by epergo** [comment]
`gem -v` will give you the version of `rubygems` you have installed, not `acts_as_votable` version

To correctly use the gem you have to add it to the `Gemfile` in your Rails application and then run `bundle install` then you'll be able to run `rails generate acts_as_votable:migration`

I'm closing this issue with it really isn't an issue. Hope you understand.

**Comment by cars10** [comment]
I can confirm that this does not work with rails 5.1.
