### ISSUE TITLE
Rails 5.2 support

### ISSUE THREAD

**Issue by danmitchell-** [ryanto/acts_as_votable#171]
I can run `bundle install` with no issues but I keep getting this error -

```
Could not find acts_as_votable-0.11.1 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by epergo** [comment]
Hi, try to remove version of the gem from Gemfile (if you have it) and run update only for `acts_as_votable`

`bundle update --source acts_as_votable`

**Comment by epergo** [comment]
Closing, if you continue to have problems feel free to comment.
