### ISSUE TITLE
Adding a custom field to votes

### ISSUE THREAD

**Issue by Dercni** [ryanto/acts_as_votable#179]
Repost from : https://stackoverflow.com/questions/48473584/adding-a-custom-field-to-votes

I use the acts as voteable gem to record both likes/dislikes against a model and votes for a model. Models can have multiple voting options.

I now have a situation where I need to record the user's location at the time a vote is cast. The user may change their location after voting so this need to be stored wit the vote, not referenced via the user.

Is it possible to add a custom field to the table and then create an after_save callback to store the location?

**Comment by ryanto** [comment]
For this one I would recommend attaching votes to another model that can track a user and a location.
