### ISSUE TITLE
undefined local variable or method `acts_as_votable' for #<Class:0xe457858>

### ISSUE THREAD

**Issue by monakate** [ryanto/acts_as_votable#182]
Hi I added the gem 'acts_as_votable', '~> 0.11.1' in my Gemfile.
Then, I ran bundle install.

However, if I put acts_as_votable in my Model:

Event < ApplicationRecord
	acts_as_votable

It returns a NameError. 

I was wondering if its my rails' version? I'm in rails' version 6 and it is not supported? If so, can you please make a supported version of the gem in rails 6? Thank you!

**Comment by cgibsonmm** [comment]
Any chance for more information? link to your git repo anything?

**Comment by epergo** [comment]
@monakate Any chance for more information?
Rails version (you talk about Rails 6, but that version has not been released yet)
Ruby version
Gem version

**Comment by epergo** [comment]
Closing as this is stale.

@monakate feel free to create a new issue if you have more problems.
