### ISSUE TITLE
Using with UUID's as primary key

### ISSUE THREAD

**Issue by ckorhonen** [ryanto/acts_as_votable#183]
Just a note for anyone using UUIDs out there, you will need to change the generated database migration to something like the example below, since `t.references :column` assumes that you are using integers.

Might be worth mentioning in the Readme, wanted to post it here in case anyone runs into this issue.

``` ruby
class ActsAsVotableMigration < ActiveRecord::Migration[4.2]
  def self.up
    create_table :votes do |t|
      t.string :votable_type
      t.string :voter_type
      t.uuid :votable_id
      t.uuid :voter_id

      t.boolean :vote_flag
      t.string :vote_scope
      t.integer :vote_weight

      t.timestamps
    end

    add_index :votes, [:voter_id, :voter_type, :vote_scope]
    add_index :votes, [:votable_id, :votable_type, :vote_scope]
  end

  def self.down
    drop_table :votes
  end
end
```

**Comment by marknguyen01** [comment]
` t.references :votable, type: :string, :polymorphic => true`
My votable_id is a string but it only records the first integer digits?

**Comment by ryanto** [comment]
Very nice! Thank you for sharing this, I'm sure it will help others.
