### ISSUE TITLE
N+1 problem with my voters votes.

### ISSUE THREAD

**Issue by ccoeder** [ryanto/acts_as_votable#184]
Hi,

I have posts that can be votable. And I have voters which is signed in devise users. I need to know who votes what so I can change the color of buttons or anything. But I have **n+1** problem. How can I solve this? 

```
class PostSerializer < ActiveModel::Serializer
  belongs_to :user

  attributes :id, :title, :content, :is_votable, :is_voted, :cached_votes_total, :cached_votes_up, :cached_votes_down, :created_at, :updated_at

  def is_voted
    return scope.voted_as_when_voted_for object if object.is_votable && object.cached_votes_total > 0

    nil
  end
end
```

How can I eager load who votes what? 

Thank you.

**Comment by ccoeder** [comment]
I've solved this without going to db. But I don't like it. 

```
  def voted_for
    vote = object.votes_for.select { |vote| vote.voter_id == scope.id }.first

    if not vote.nil?
      return vote.vote_flag
    else
      return nil
    end
  end
```

**Comment by epergo** [comment]
Sorry I've been very busy, just to give you my 2 cents:

You could rewrite it like this:

```ruby
  def voted_for
    vote = object.votes_for.detect { |vote| vote.voter_id == scope.id }
    
    vote ? vote.flag : nil
  end
```

`detect` is the same as `select.first` but faster and the ternary operator makes it clearer (this is super ultra subjective)

**Comment by epergo** [comment]
If in your code `scope` means the current user you want to filter by, yes, I think is correct. But I'm missing what `scope` means in your codebase.

**Comment by ccoeder** [comment]
Yes, scope is current user.

**Comment by fongfan999** [comment]
Hi there, I'm also having this problem. Your suggestion will work, but it still causes N+1, which is very inefficient.

Is there any better workaround? Thank you so much for your help 🙇
