### ISSUE TITLE
acts_as_votable issue

### ISSUE THREAD

**Issue by jneuenschwander** [ryanto/acts_as_votable#185]
I try running rake db:migrate after  submitting rails g acts_as_votable:migrate and it continues showing me this error
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class ActsAsVotableMigration < ActiveRecord::Migration[4.2]
C:/Users/JNYGM03/ChallengeRubyOnRails/Reddit/db/migrate/20181008015955_acts_as_votable_migration.rb:1:in `<top (required)>'

Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class ActsAsVotableMigration < ActiveRecord::Migration[4.2]
C:/Users/*****/RubyOnRails/Reddit/db/migrate/20181008015955_acts_as_votable_migration.rb:1:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

Can you help me solve this issue?

**Comment by epergo** [comment]
Hello! Which version of the have do you have installed?

**Comment by jneuenschwander** [comment]
Hello the versión I have for the gem is 'acts_as_votable', '~> 0.10.0' and my version of rails is the 5.2.1

**Comment by epergo** [comment]
Update it to the last version please (0.11.1) https://rubygems.org/gems/acts_as_votable

Remove all migrations from acts_as_votable and run the generator again

**Comment by jneuenschwander** [comment]
It worked ! Thank you for helping me.

**Comment by epergo** [comment]
🎉
