### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by nfedyashev** [ryanto/acts_as_votable#189]
Is it possible to establish CHANGELOG.md convention for new releases?

It's a bit unhandy to verify the actual commits in git history between releases.

**Comment by epergo** [comment]
This time I listed all changes in the release details https://github.com/ryanto/acts_as_votable/releases but you are right, we should create a CHANGELOG.md.

Will do next time!

**Comment by nfedyashev** [comment]
This issue seems to be fixed thanks to efforts from @epergo and @ryanto
Thank you
