### ISSUE TITLE
current_user.voted_for? @post returns false regardless of vote

### ISSUE THREAD

**Issue by masudhossain** [ryanto/acts_as_votable#190]
post.rb 
`acts_as_votable`

user.rb
`acts_as_voter`

The vote registers fine and doing `<%= @post.weighted_score %>` shows the correct amount as well. But when doing `<%= current_user.voted_for? @post  %>` it shows the incorrect boolean.

**Comment by ryanto** [comment]
Is this still happening? I know that we have some good test coverage around voted_for (https://github.com/ryanto/acts_as_votable/blob/00ec6f44d60ede0b8c3bf1998b31355070718d86/spec/shared_example/voter_model.rb#L9). Feel free to reopen with a failing test or repo that reproduces this and I'll take a look.
