### ISSUE TITLE
0.12.0 => 0.12.1 version upgrade is a bit painful

### ISSUE THREAD

**Issue by nfedyashev** [ryanto/acts_as_votable#204]
Still love your gem, just a minor comment on 0.12.0 => 0.12.1 version upgrade pain points.

Before upgrading from 0.12.0 to 0.12.1 I checked the changelog at https://github.com/ryanto/acts_as_votable/releases

and corresponding pull requests
>#202 #198 Rails 6 (@BillyParadise @murny)
>#201 #200 Gem cleanup (@olleolleolle)

Failure message wasn't very helpful without checking the source code
```
Failure/Error: acts_as_votable cacheable_strategy: :update_attributes

ArgumentError:
  update_attributes
# ./app/models/entry.rb:48:in `<class:Entry>'
```

that's how I found this important commit that somehow wasn't mentioned in the changelog 
https://github.com/ryanto/acts_as_votable/commit/80d8296d5964380bb54b5441b495f4cbfd5e99b6

It doesn't feel like a patch-level version upgrade because it is not backward compatible.

**Comment by nfedyashev** [comment]
@ryanto 
the fix was to change rename cacheable strategy

```diff
< cacheable_strategy: update_attributes
> cacheable_strategy: :update
```

**Comment by ryanto** [comment]
Ok thank you for that. I finally got this one documented in the releases :)
