### ISSUE TITLE
undefined local variable or method `acts_as_votable' 

### ISSUE THREAD

**Issue by mike1011** [ryanto/acts_as_votable#206]
I have a Rails 5.2.3 app and `acts_as_votable` of `0.12.1` version.There are two problems that I faced...

- Migration does not run with the error shown as below -

```
ubuntu:~/environment/myapp (new_layout) $ rails generate acts_as_votable:migration
Running via Spring preloader in process 2422
Could not find generator 'acts_as_votable:migration'. Maybe you meant 'active_record:migration', 'acts_as_follower' or 'migration'
Run `rails generate --help` for more options.
```

- `acts_as_votable` comes undefined when added to a model(added `acts_as_votable` to `video.rb`).

```
[2.6.3 :001 > Video.new
Traceback (most recent call last):
        3: from (irb):1
        2: from app/models/video.rb:1:in `<main>'
        1: from app/models/video.rb:12:in `<class:Video>'
NameError (undefined local variable or method `acts_as_votable' for Video (call 'Video.connection' to establish a connection):Class)
Did you mean?  acts_as_taggable
2.6.3 :002 > ](url)
```

I had to manually create migration files by copying those from `lib/generators` folder which is Ok but why the second problem..not sure.
Can someone put some light on this?

Thanks in advance.

**Comment by ryanto** [comment]
Hi, thanks for the issue!

Do you mind putting together a small reproduction repo that shows these problems? That would make debugging this a bit easier.

Thanks again!

**Comment by mike1011** [comment]
Just to update ,.. this error only comes on rails console but when I started my application with the gems installed, it worked but somehow its not testable on rails console.

any idea?

**Comment by ryanto** [comment]
Not sure. I'm going to close this issue since I cannot reproduce it, but if this comes up for anyone else feel free to add details.

**Comment by citizens** [comment]
I encountered the `Could not find generator 'acts_as_votable:migration'.` issue after adding the gem to a Rails 6 app. However, running `bin/spring stop` and re-running `rails generate acts_as_votable:migration` solved the problem for me.
