### ISSUE TITLE
Update CI matrix

### ISSUE THREAD

**Issue by fatkodima** [ryanto/acts_as_votable#210]
For newer rubies and railses.

Maybe it will be a good idea to move away from travis? While I love travis, but there was a drama with them a while back (acquired, seems to be closing?) and new native GitHub actions were introduced.

**Comment by ryanto** [comment]
Yup, totally agree. Travis is just too slow. I can work on getting us onto GH actions.

What are you thinking for newer rails/rubies? Should we drop rails 4?

**Comment by fatkodima** [comment]
While it doesn't hurt much to support this library for older rubies/railses, I would prefer to drop EOLed rubies (https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/) and railses (https://guides.rubyonrails.org/maintenance_policy.html) < 5.2. 
This will also stimulate people to upgrade their apps. 😄

**Comment by ryanto** [comment]
Ok great! I got it moved over to actions in #213.
