### ISSUE TITLE
Multiple different reactions?

### ISSUE THREAD

**Issue by staleo** [ryanto/acts_as_votable#216]
Just out of curiosity: how would you guys implement discord-like multiple reactions to, let's say, post? Like, not just a boolean like or dislike, but instead a set of different emotional reactions, like sadness, laugh, anger, +100, etc?

**Comment by ryanto** [comment]
Hi there!

I've implemented reactions in a few rails projects, I do not think `acts_as_votable` is the right tool for this job.

If I were you I'd start with a `Reaction` model that links a user to a post (or a polymorphic reactable). From there you can log the reaction (thumbs up, thumbs down, emoji, etc) and tie it to the user and post.

```ruby
class Reaction
  # database columns :reaction
  belongs_to :user 
  belongs_to :post
end

user = User.first
post = Post.fist
Reaction.find_or_create_by(reaction: "👍" user: user, post: post)
```

**Comment by staleo** [comment]
Yea Ryan, looks like you're right. I came up with this setup: models Like and LikeType, and LikeType `has_one_attached :image`. Not the biggest deal in terms of efforts, however it's always nice to have a properly designed and ready-to-use solution just one `bundle i` away, right like `acts_as_votable`. :heart:

**Comment by ryanto** [comment]
Awesome! Glad to hear you got it figured out!
