### ISSUE TITLE
Mutual exclusion

### ISSUE THREAD

**Issue by ahnbizcad** [ryanto/acts_as_votable#80]
I wasn't sure where to post new features suggestions/questions. Please excuse me if I am polluting the issues board.

1)
Currently scopes are independent. This is useful for votes like on yelp, where you can vote for "useful", "funny", "cool", and so on. But for creating a poll, mutual exclusion is necessary for a handful of specified scopes. Can this gem do this?

I am trying to use this gem as a polling system. In such, I will use a named scope for an option, but I want a given collection of named to be mutually exclusive. I envision the command to do this something along the lines of: 

`mutually_exclusive( 'collection_1', [ 'scope_1', 'scope_2', 'scope_3'], 2)`

the array of scope names would be existing scopes that will become mutually exclusive, so that a voter cannot vote for more than one of those scopes. 

Additionally, the default number of votes for a pool would be 1, but could be specified to be a greater integer). In the above example, a 3rd argument, an integer would specify this.

The first argument, 'collection_1' would be the new scope name representing the collection of these basic scopes. This would be useful when trying to make this scope mutually exclusive with other scopes. In other words, you would be able to take the string 'collection_1' and make that set of scopes mutually exclusive with other scopes (or scope sets) like 'collection_2' as well. 

`mutually_exclusive( 'collection_set_1', [ 'collection_1', 'collection_2', 'scope_4', 'scope_4'], 3)`

As you can see, by using the same format for the scope collection as a plain old scope, it allows for easy chaining by being able to pass it into the same method.

I want to create a pull request myself, but I am not up to speed on the workings of this gem. I've looked through every file in this gem, but am not sure I understand everything. Also, it would be my first open source contribution. But if no one is planning to implement this, I am definitely going to try to create this myself. I would enjoy collaborating or getting some hints to accomplish mutual exclusion

I'd be glad to clarify anything that may have not been worded clearly.

**Comment by ryanto** [comment]
Thanks for this issue. It's been a few years and I don't think this is a feature we can currently support. I'm going to close this one.
