### ISSUE TITLE
caching not working as expected

### ISSUE THREAD

**Issue by thatfunkymunki** [ryanto/acts_as_votable#82]
I ran the migration as shown in the readme, but whenever I do  object.get_likes.size it still queries the votes table without hitting the cache. Additionally the cache columns are not automatically updating with new votes. Are there any procedures to perform?

<strong>Score:</strong> <%=@card.get_likes.size - @card.get_dislikes.size%>
  <strong>Cached Score: </strong> <%=@card.cached_votes_up.size - @card.cached_votes_down.size%>

**Comment by clairity** [comment]
if anyone else runs into this issue of the cache seemingly not working, a restart of the rails server just might fix it. =)

**Comment by YouckFou46** [comment]
Hi,
i have a similar problem, maybe someone can help.
Displaying the cached_weighted score in show, there is no problem.
BUT as soon as i try to order/reorder int wont work
i tried running this:
@movie_suggestions.order(:cached_weighted_score => :desc)
@movie_suggestions.order('cached_weighted_score DESC')
@movie_suggestions.reorder(:cached_weighted_score => :desc)
@movie_suggestions.reorder('cached_weighted_score DESC')
@movie_suggestions.reorder(:weighted_score => :desc)
@movie_suggestions.order(:weighted_score => :desc)
 all of this doesnt work, although the value of a single suggestion is displayed correctly in view using this:
 suggestion.weighted_score
 any suggestions on why it wont work?

**Comment by vietqhoang** [comment]
> Hi,
> i have a similar problem, maybe someone can help.
> Displaying the cached_weighted score in show, there is no problem.
> BUT as soon as i try to order/reorder int wont work
> i tried running this:
> @movie_suggestions.order(:cached_weighted_score => :desc)
> @movie_suggestions.order('cached_weighted_score DESC')
> @movie_suggestions.reorder(:cached_weighted_score => :desc)
> @movie_suggestions.reorder('cached_weighted_score DESC')
> @movie_suggestions.reorder(:weighted_score => :desc)
> @movie_suggestions.order(:weighted_score => :desc)
> all of this doesnt work, although the value of a single suggestion is displayed correctly in view using this:
> suggestion.weighted_score
> any suggestions on why it wont work?

Do you have a default scope set on your `MovieSuggestion` model? Have you tried chaining `to_sql` to any of your calls to see what the SQL output is like? It may reveal what the issue is.

**Comment by YouckFou46** [comment]
The problem was in the migration, somehow. Try and rewrite it that might help

**Comment by jDeppen** [comment]
The issue for me was that I was only utilizing `vote_weight` as star rating, so I left `vote_flag: nil`. I needed to set `vote_flag` in order for the cache to update these:
```
cached_weighted_average # vote_flag must be true for the vote to count
cached_votes_total # vote_flag can't be nil or the vote won't count
```
note: `cached_weighted_total` worked fine with `vote_flag: nil`
(these are the only three cache columns I'm using, so I can't speak to the others)
