### ISSUE TITLE
Adding acts_as_votable to model cause activity records doubling when using public_activity gem

### ISSUE THREAD

**Issue by ghost** [ryanto/acts_as_votable#89]
Hey,

I'm using acts_as_votable for my Song class so people can like/dislike songs, and also using public_activity to record when they add song to favourites.

Although I'm using different functions to up/down-vote and _add to favourites_ a song and in _add to favourites_ method I'm not using any code related with acts_as_votable gem.

**The problem here is that if model has "acts_as_votable" the recorded activity is doubled.**

Nonetheless, we are all coders, so code describe it best

**Music::SongsController**

``` ruby
def vote
    @song = Music::Song.find(params[:song_id])

    if current_user.voted_for? @song
      @song.unliked_by current_user
      render text: "unliked"
    else
      @song.liked_by current_user
      @song.create_activity :fav, owner: current_user 

      render text: "liked"
    end
  end

def favourite
    @song = Music::Song.find(params[:song_id])
    @song.create_activity :pin, owner: current_user 

    redirect_to current_user, notice: "Ok"
  end
```

``` ruby
class Music::Song < ActiveRecord::Base
  include Importable, Exportable
  include PublicActivity::Common

  # --- Acts ---
  acts_as_taggable
  #acts_as_votable           # Commented as this is the one causing problems
```

I guess it may have something in common with #83

**Comment by ryanto** [comment]
Think this one is now fixed.
