### ISSUE TITLE
uninitialized constant User::Vote

### ISSUE THREAD

**Issue by malditojavi** [ryanto/acts_as_votable#96]
Hi, I'm running into an issue with active_admin implementation. I reviewed some of the links listed in a [similar issue](https://github.com/ryanto/acts_as_votable/issues/46) but didn't find a solution.

my gem file has a higher version of act_as_votable than the one suggested as solution in that thread

gem 'acts_as_votable', '~> 0.10.0'
gem 'activeadmin', github: 'gregbell/active_admin'

my **model > user.rb** looks like 
          class User < ActiveRecord::Base
          TEMP_EMAIL_PREFIX = 'change@me'
          TEMP_EMAIL_REGEX = /\Achange@me/
          include Gravtastic
          gravtastic

```
      acts_as_voter

      devise :database_authenticatable, :registerable,
             :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :confirmable
       ...
      def self.find_for_oauth(auth, signed_in_resource = nil)

        identity = Identity.find_for_oauth(auth)

        user = signed_in_resource ? signed_in_resource : identity.user

        if user.nil?

          email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
          email = auth.info.email if email_is_verified
          user = User.where(:email => email).first if email

          # Create the user if it's a new registration
          if user.nil?
            user = User.new(
              name: auth.extra.raw_info.name,
              username: auth.extra.raw_info.screen_name,
              email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
              password: Devise.friendly_token[0,20]
            )
            user.skip_confirmation!
            user.save!
          end
        end

        # Associate the identity with the user if needed
        if identity.user != user
          identity.user = user
          identity.save!
        end
        user
      end

      def email_verified?
        self.email && self.email !~ TEMP_EMAIL_REGEX
      end

      include TheComments::User

      has_many :hacks
      has_many :comments

      def admin?
        self == User.first
      end

      def comments_admin?
        admin?
      end

      def comments_moderator? comment
        id == comment.holder_id
      end
    end
```

And my trace outputs this

/Users/javier/Desktop/definitive/app/admin/votes.rb:1:in `<top (required)>': uninitialized constant Vote (NameError)
    from /Users/javier/.rvm/gems/ruby-2.1.2/bundler/gems/active_admin-83059dc2894b/lib/active_admin/application.rb:179:in`block in load'
    from /Users/javier/.rvm/gems/ruby-2.1.2/bundler/gems/active_admin-83059dc2894b/lib/active_admin/error.rb:40:in `capture'
    from /Users/javier/.rvm/gems/ruby-2.1.2/bundler/gems/active_admin-83059dc2894b/lib/active_admin/application.rb:179:in`load'
    from /Users/javier/.rvm/gems/ruby-2.1.2/bundler/gems/active_admin-83059dc2894b/lib/active_admin/application.rb:171:in `block in load!

Any idea how to tackle this issue? Repo can be found [here](https://github.com/malditojavi/petithacks).

**Comment by epergo** [comment]
Closing this issue because its 3 years old and the example repo is not available anymore.

Feel free to open a new issue if the problem persists.

Thanks!
